export const responseAll = [
    {
        city: "",
        district: "CENTRO",
        full_address: "19, CENTRO, PR, 81265-220",
        number: "19",
        postcode: "81265-220",
        region: "PR",
        street: "",
        unit: "",
    },
    {
        city: "PORTO ALEGRE",
        district: "",
        full_address: "RUA BARAO DO COTEGIPE, 43, APARTAMENTO 04, PORTO ALEGRE, 90540-020",
        number: "43",
        postcode: "90540-020",
        region: "",
        street: "RUA BARAO DO COTEGIPE",
        unit: "APARTAMENTO 04",
    },
    {
        city: "JOINVILLE",
        district: "",
        full_address: "RUA EXPEDICIONARIO REINOLDO MILLNITZ, CASA, JOINVILLE, SC",
        number: "",
        postcode: "",
        region: "SC",
        street: "RUA EXPEDICIONARIO REINOLDO MILLNITZ",
        unit: "CASA",
    },
];
