import { ResponseEntity } from "../../../../../src/domain/rules/response";

export const validLocalReceived = [
    {
        place_id: 66933355,
        licence: "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
        osm_type: "node",
        osm_id: 6177641338,
        boundingbox: ["-25.4178293", "-25.4177293", "-49.2380988", "-49.2379988"],
        lat: "-25.4177793",
        lon: "-49.2380488",
        display_name:
            "444, Rua Manoel Correia de Freitas, Jardim Social, Curitiba, Região Geográfica Imediata de Curitiba, Região Metropolitana de Curitiba, Região Geográfica Intermediária de Curitiba, Paraná, Região Sul, 82530230, Brasil",
        class: "place",
        type: "house",
        importance: 0.711,
        address: {
            house_number: "444",
            road: "Rua Manoel Correia de Freitas",
            suburb: "Jardim Social",
            city: "Curitiba",
            municipality: "Região Geográfica Imediata de Curitiba",
            county: "Região Metropolitana de Curitiba",
            state_district: "Região Geográfica Intermediária de Curitiba",
            state: "Paraná",
            region: "Região Sul",
            postcode: "82530230",
            country: "Brasil",
            country_code: "br",
        },
    },
    {},
    {
        address: {
            town: "Curitiba",
        },
    },
];

export const validLocalResponse: ResponseEntity[] = [
    {
        accuracy: 0.711,
        city: "Curitiba",
        country: "Brasil",
        district: "Jardim Social",
        fullAddress:
            "444, Rua Manoel Correia de Freitas, Jardim Social, Curitiba, Região Geográfica Imediata de Curitiba, Região Metropolitana de Curitiba, Região Geográfica Intermediária de Curitiba, Paraná, Região Sul, 82530230, Brasil",
        latNorthBBox: -25.4177293,
        latSouthBBox: -49.2379988,
        latitude: -25.4177793,
        longEastBBox: -25.4178293,
        longWestBBox: -49.2380988,
        longitude: -49.2380488,
        number: "444",
        placeType: "house",
        publicPlace: "Rua Manoel Correia de Freitas",
        state: "Paraná",
        zipCode: "82530230",
    },
    {
        accuracy: undefined,
        city: undefined,
        country: undefined,
        district: undefined,
        fullAddress: undefined,
        latNorthBBox: undefined,
        latSouthBBox: undefined,
        latitude: undefined,
        longEastBBox: undefined,
        longWestBBox: undefined,
        longitude: undefined,
        number: undefined,
        publicPlace: undefined,
        state: undefined,
        zipCode: undefined,
    },
    {
        accuracy: undefined,
        city: "Curitiba",
        country: undefined,
        district: undefined,
        fullAddress: undefined,
        latNorthBBox: undefined,
        latSouthBBox: undefined,
        latitude: undefined,
        longEastBBox: undefined,
        longWestBBox: undefined,
        longitude: undefined,
        number: undefined,
        publicPlace: undefined,
        state: undefined,
        zipCode: undefined,
    },
];
