import { ResponseEntity } from "../../../../../src/domain/rules/response";

export const validLocalReceived = {
    features: [
        {
            geometry: {
                type: "Point",
                coordinates: [-49.242356, -25.400258],
            },
            properties: {
                id: "polyline:23868159",
                gid: "openstreetmap:street:polyline:23868159",
                layer: "street",
                source: "openstreetmap",
                source_id: "polyline:23868159",
                name: "Rua Desembargador Arthur Leme",
                housenumber: "19",
                street: "Rua Desembargador Arthur Leme",
                postalcode: "65870-000",
                confidence: 0.8,
                match_type: "fallback",
                accuracy: "centroid",
                country: "Brasil",
                country_gid: "whosonfirst:country:85633009",
                country_a: "BRA",
                macroregion: "Sul",
                macroregion_gid: "whosonfirst:macroregion:1511777409",
                region: "Paraná",
                region_gid: "whosonfirst:region:85681983",
                region_a: "PR",
                county: "Curitiba",
                county_gid: "whosonfirst:county:102057617",
                localadmin: "Curitiba",
                localadmin_gid: "whosonfirst:localadmin:404561111",
                locality: "Curitiba",
                locality_gid: "whosonfirst:locality:101957995",
                neighbourhood: "Cabral",
                neighbourhood_gid: "whosonfirst:neighbourhood:85766691",
                continent: "América do Sul",
                continent_gid: "whosonfirst:continent:102191577",
                label: "Rua Desembargador Arthur Leme, Curitiba, PR, Brasil",
            },
            bbox: [-49.243758, -25.402046, -49.240989, -25.398492],
        },
        {},
    ],
};

export const validLocalResponse: ResponseEntity[] = [
    {
        accuracy: 0.8,
        city: "Curitiba",
        country: "Brasil",
        district: "Cabral",
        fullAddress: "Rua Desembargador Arthur Leme, Curitiba, PR, Brasil",
        latNorthBBox: -25.402046,
        latSouthBBox: -25.398492,
        latitude: -25.400258,
        longEastBBox: -49.243758,
        longWestBBox: -49.240989,
        longitude: -49.242356,
        number: "19",
        placeType: undefined,
        publicPlace: "Rua Desembargador Arthur Leme",
        state: "Paraná",
        zipCode: "65870-000",
    },
    {
        accuracy: undefined,
        city: undefined,
        country: undefined,
        district: undefined,
        fullAddress: undefined,
        latNorthBBox: undefined,
        latSouthBBox: undefined,
        latitude: undefined,
        longEastBBox: undefined,
        longWestBBox: undefined,
        longitude: undefined,
        number: undefined,
        publicPlace: undefined,
        state: undefined,
        zipCode: undefined,
    },
];
